//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GününYemeğiTablosu
    {
        public int GYemekID { get; set; }
        public string GYemekAd { get; set; }
        public string GYemekMalzeme { get; set; }
        public string GYemekTarif { get; set; }
        public Nullable<byte> GYemekPuan { get; set; }
        public System.DateTime GYemekTarih { get; set; }
        public string GYemekResim { get; set; }
    }
}
