//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MesajTablosu
    {
        public int MesajID { get; set; }
        public string MesajMail { get; set; }
        public string Mesajİçerik { get; set; }
    }
}
