//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Yemek_Sitesi_VeritabanıEntities1 : DbContext
    {
        public Yemek_Sitesi_VeritabanıEntities1()
            : base("name=Yemek_Sitesi_VeritabanıEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GününYemeğiTablosu> GününYemeğiTablosu { get; set; }
        public virtual DbSet<HakkımızdaTablosu> HakkımızdaTablosu { get; set; }
        public virtual DbSet<KategoriTablosu> KategoriTablosu { get; set; }
        public virtual DbSet<MesajTablosu> MesajTablosu { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TarifVermeTablosu> TarifVermeTablosu { get; set; }
        public virtual DbSet<YemekTablosu> YemekTablosu { get; set; }
        public virtual DbSet<YorumlarTablosu> YorumlarTablosu { get; set; }
        public virtual DbSet<YöneticiTablosu> YöneticiTablosu { get; set; }
    }
}
