//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifVermeTablosu
    {
        public int TarifID { get; set; }
        public string Ad { get; set; }
        public string Malzeme { get; set; }
        public string TarifYapılış { get; set; }
        public string TarifKişi { get; set; }
        public string TarifResim { get; set; }
        public string TarifKişiMail { get; set; }
        public Nullable<bool> TarifOnay { get; set; }
    }
}
