//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Sitesi_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YemekTablosu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YemekTablosu()
        {
            this.YorumlarTablosu = new HashSet<YorumlarTablosu>();
        }
    
        public int YemekID { get; set; }
        public string YemekAd { get; set; }
        public string Malzemeler { get; set; }
        public string Tarifler { get; set; }
        public string Resimler { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public Nullable<byte> Puan { get; set; }
        public int KategoriID { get; set; }

        public string tempCommentMail { get; set; }
        public string tempCommentContent { get; set; }

        public virtual KategoriTablosu KategoriTablosu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YorumlarTablosu> YorumlarTablosu { get; set; }
    }
}
