//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kütüphane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlınanKitapTablosu
    {
        public int ID { get; set; }
        public System.DateTime KitapAlınmaTarihi { get; set; }
        public string KitabıAlanKullanıcı { get; set; }
        public string AlınanKitapAdı { get; set; }
    }
}
