//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kütüphane.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KütüphaneKullanıcıTablosu2
    {
        public int ID { get; set; }

        [Required(ErrorMessage ="Mail adresi boş bırakılamaz")]
        public string GirişBilgisi { get; set; }

        [Required(ErrorMessage ="Şifre boş bırakılamaz")]
        public string Şifre { get; set; }

        [Required(ErrorMessage ="Ad boş bırakılamaz")]
        public string Ad { get; set; }

        [Required(ErrorMessage ="Soyad boş bırakılamaz")]
        public string Soyad { get; set; }


        public byte Rank { get; set; }
    }
}
