//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Kütüphane.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KütüphaneKitapTablosu
    {
        public int ID { get; set; }
        public string KitapAdı { get; set; }
        public int SayfaSayısı { get; set; }
        public string Kategori { get; set; }
        public string Yazar { get; set; }
        public int KitapYılı { get; set; }
        public int KitapAdeti { get; set; }
    }
}
