//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Deneme_ArabaSitesi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ArabaYoutubeEntities1 : DbContext
    {
        public ArabaYoutubeEntities1()
            : base("name=ArabaYoutubeEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TableBrand> TableBrand { get; set; }
        public virtual DbSet<TableCar> TableCar { get; set; }
        public virtual DbSet<TableContact> TableContact { get; set; }
        public virtual DbSet<TableUser> TableUser { get; set; }
    }
}
