//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Deneme_ArabaSitesi.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableCar
    {
        public int CarID { get; set; }

        [Required]
        public string CarModel { get; set; }

        [Required]
        public int CarBrandID { get; set; }

        [Required]
        public string CarFuelType { get; set; }

        [Required]
        public string CarDescription { get; set; }

        [Phone]
        [Required]
        public string CarContact { get; set; }

        [Required]
        public string CarSeller { get; set; }

        [Required]
        public string CarPhoto { get; set; }

        [Required]
        public int CarPrice { get; set; }

        public bool CarConfirmation { get; set; }
    
        public virtual TableBrand TableBrand { get; set; }
    }
}
