//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_Car_Selling_Template.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutAndContact
    {
        public int AboutID { get; set; }
        public string AboutDescription { get; set; }
        public string ContactMail { get; set; }
        public string ContactNumber { get; set; }
    }
}
