//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNTABLOSU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUNTABLOSU()
        {
            this.SATISTABLOSU = new HashSet<SATISTABLOSU>();
        }
    
        public int URUNID { get; set; }
        public string URUNAD { get; set; }
        public Nullable<int> KATEGORIID { get; set; }
        public Nullable<int> URUNFIYAT { get; set; }
        public Nullable<int> URUNSTOK { get; set; }
    
        public virtual KATEGORITABLOSU KATEGORITABLOSU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATISTABLOSU> SATISTABLOSU { get; set; }
    }
}
